### ISSUE TITLE
Custom mouse pointer

### ISSUE THREAD

**Issue by NaveenKarippai** [szhu/3030#21]
Just curious and a noob question: Is it possible to create a _custom mouse pointer_ ?

**Comment by AaronCritchley** [comment]
Yes, but:
- It's not an issue in this repo
- It's not an issue at all, it's a request
- It's not related at all to this repo

I'm not sure if I'm misunderstanding you, but if you literally want a custom mouse pointer, Google it (and close this issue). Please try to expand on what you're trying to say if I have misunderstood.

**Comment by NaveenKarippai** [comment]
True! I should have requested for a discussion. Thanks.
I will make a custom mouse pointer on my own.

**Comment by NaveenKarippai** [comment]
My point was to create a custom mouse pointer (like a car)  and replace bear wtih road. It turns into cool game.

**Comment by AaronCritchley** [comment]
Ah ok, so I did misunderstand. 

To the best of my knowledge it's not possible in the games current format (a README), there's some other cute features people have suggested but it seems like @szhu wants to keep the game as pure as possible. You could always make your own alternative with a car/road and see how it turns out! :smile:

**Comment by szhu** [comment]
Thanks for answering, @AaronCritchley, and you're pretty much right!

@NaveenKarippai, you're free to make a fork of this and add whatever features you want. As you probably noticed, this game isn't like other games, in that its goal is to turn a serious Chrome bug humorous, and as such I won't really be developing the game further since the bug is fixed and there are much better maze games out there.

However, if you do end up building a feature, feel free to send in a pull request (as @AaronCritchley did in #19), and if it looks cool I can integrate it!
